### Problem Statement

XYZ Co's 2014-18 sales data to identify key revenue and profit drives across products, channels, and regions, uncover seasonal trends and outliers, and align performance against budgets. Use these insights to optimze pricing, promotions and market expansion for sutainable growth and reduced concentration risk.

### Importing data set

In [1]:
# Importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn

In [2]:
dataset_url = r".\assets\Regional Sales Dataset.xlsx"
sheets = pd.read_excel(dataset_url, sheet_name=None)

In [3]:
sheets

{'Sales Orders':         OrderNumber  OrderDate  Customer Name Index      Channel  \
 0       SO - 000225 2014-01-01                  126    Wholesale
 1      SO - 0003378 2014-01-01                   96  Distributor
 2      SO - 0005126 2014-01-01                    8    Wholesale
 3      SO - 0005614 2014-01-01                   42       Export
 4      SO - 0005781 2014-01-01                   73    Wholesale
 ...             ...        ...                  ...          ...
 64099  SO - 0007573 2018-02-28                   74    Wholesale
 64100  SO - 0007706 2018-02-28                   51       Export
 64101  SO - 0007718 2018-02-28                  136  Distributor
 64102  SO - 0008084 2018-02-28                  158  Distributor
 64103  SO - 0008654 2018-02-28                   22  Distributor

       Currency Code Warehouse Code  Delivery Region Index  \
 0               USD         AXW291                    364
 1               USD         AXW291                    488
 2               USD         AXW291                    155
 3               USD         AXW291                    473
 4               USD         AXW291                    256
 ...             ...            ...                    ...
 64099           USD         AXW291                    825
 64100           USD         NXH382                    444
 64101           USD         AXW291                    312
 64102           USD         AXW291                    737
 64103           USD         AXW291                    807

        Product Description Index  Order Quantity  Unit Price  Line Total  \
 0                             27               6      2499.1     14994.6
 1                             20              11      2351.7     25868.7
 2                             26               6       978.2      5869.2
 3                              7               7      2338.3     16368.1
 4                              8               8      2291.4     18331.2
 ...                          ...             ...         ...         ...
 64099                         26              12      1815.7     21788.4
 64100                         21               6       864.3      5185.8
 64101                         13              11      3953.0     43483.0
 64102                         20               7      3959.7     27717.9
 64103                         15               8       998.3      7986.4

        Total Unit Cost
 0             1824.343
 1             1269.918
 2              684.740
 3             1028.852
 4             1260.270
 ...                ...
 64099          980.478
 64100          579.081
 64101         2648.510
 64102         2930.178
 64103          848.555

 [64104 rows x 12 columns],
 'Customers':      Customer Index Customer Names
 0                 1  Geiss Company
 1                 2  Jaxbean Group
 2                 3     Ascend Ltd
 3                 4      Eire Corp
 4                 5   Blogtags Ltd
 ..              ...            ...
 170             171   Accord Group
 171             172   BB17 Company
 172             173          H Ltd
 173             174   Tekfly Group
 174             175   SHISEIDO Ltd

 [175 rows x 2 columns],
 'Regions':       id        name                                   county state_code  \
 0      1      Auburn                               Lee County         AL
 1      2  Birmingham           Shelby County/Jefferson County         AL
 2      3     Decatur           Limestone County/Morgan County         AL
 3      4      Dothan  Dale County/Houston County/Henry County         AL
 4      5      Hoover           Shelby County/Jefferson County         AL
 ..   ...         ...                                      ...        ...
 989  990      Racine                            Racine County         WI
 990  991    Waukesha                          Waukesha County         WI
 991  992  West Allis                         Milwaukee County         WI
 992  993      Casper                           Natrona County         WY
 993  994    Cheyenne                           Laramie County         WY

          state  type  latitude  longitude  area_code  population  households  \
 0      Alabama  City  32.60986  -85.48078        334       62059       21767
 1      Alabama  City  33.52744  -86.79905        205      212461       89972
 2      Alabama  City  34.57332  -86.99214        256       55437       22294
 3      Alabama  City  31.23370  -85.40682        334       68567       25913
 4      Alabama  City  33.37695  -86.80558        205       84848       32789
 ..         ...   ...       ...        ...        ...         ...         ...
 989  Wisconsin  City  42.72613  -87.78285        262       77742       29851
 990  Wisconsin  City  43.01168  -88.23148        262       71970       28331
 991  Wisconsin  City  43.01668  -88.00703        414       60620       27457
 992    Wyoming  City  42.86663 -106.31308        307       60285       23814
 993    Wyoming  City  41.13998 -104.82025        307       63335       25130

      median_income  land_area  water_area        time_zone
 0            38342  152375113     2646161  America/Chicago
 1            31061  378353942     6591013  America/Chicago
 2            41496  141006257    17594716  America/Chicago
 3            42426  232166237      835468  America/Chicago
 4            77146  122016784     2553332  America/Chicago
 ..             ...        ...         ...              ...
 989          41455   40111757     8282116  America/Chicago
 990          59547   65856921      700602  America/Chicago
 991          45221   29480532       60789  America/Chicago
 992          57790   68507280      911081   America/Denver
 993          58219   69964749      282335   America/Denver

 [994 rows x 15 columns],
 'State Regions':        Column1               Column2    Column3
 0   State Code                 State     Region
 1           AL               Alabama      South
 2           AR              Arkansas      South
 3           AZ               Arizona       West
 4           CA            California       West
 5           CO              Colorado       West
 6           CT           Connecticut  Northeast
 7           DC  District of Columbia      South
 8           DE              Delaware      South
 9           FL               Florida      South
 10          GA               Georgia      South
 11          HI                Hawaii       West
 12          IA                  Iowa    Midwest
 13          ID                 Idaho       West
 14          IL              Illinois    Midwest
 15          IN               Indiana    Midwest
 16          KS                Kansas    Midwest
 17          KY              Kentucky      South
 18          LA             Louisiana      South
 19          MA         Massachusetts  Northeast
 20          MD              Maryland      South
 21          ME                 Maine  Northeast
 22          MI              Michigan    Midwest
 23          MN             Minnesota    Midwest
 24          MO              Missouri    Midwest
 25          MS           Mississippi      South
 26          MT               Montana       West
 27          NC        North Carolina      South
 28          ND          North Dakota    Midwest
 29          NE              Nebraska    Midwest
 30          NH         New Hampshire  Northeast
 31          NJ            New Jersey  Northeast
 32          NM            New Mexico       West
 33          NV                Nevada       West
 34          NY              New York  Northeast
 35          OH                  Ohio    Midwest
 36          OK              Oklahoma      South
 37          OR                Oregon       West
 38          PA          Pennsylvania  Northeast
 39          RI          Rhode Island  Northeast
 40          SC        South Carolina      South
 41          SD          South Dakota    Midwest
 42          TN             Tennessee      South
 43          TX                 Texas      South
 44          UT                  Utah       West
 45          VA              Virginia      South
 46          WA            Washington       West
 47          WI             Wisconsin    Midwest
 48          WY               Wyoming       West,
 'Products':     Index Product Name
 0       1    Product 1
 1       2    Product 2
 2       3    Product 3
 3       4    Product 4
 4       5    Product 5
 5       6    Product 6
 6       7    Product 7
 7       8    Product 8
 8       9    Product 9
 9      10   Product 10
 10     11   Product 11
 11     12   Product 12
 12     13   Product 13
 13     14   Product 14
 14     15   Product 15
 15     16   Product 16
 16     17   Product 17
 17     18   Product 18
 18     19   Product 19
 19     20   Product 20
 20     21   Product 21
 21     22   Product 22
 22     23   Product 23
 23     24   Product 24
 24     25   Product 25
 25     26   Product 26
 26     27   Product 27
 27     28   Product 28
 28     29   Product 29
 29     30   Product 30,
 '2017 Budgets':    Product Name  2017 Budgets
 0     Product 1   3016489.209
 1     Product 2   3050087.565
 2     Product 3   2642352.432
 3     Product 4   2885560.824
 4     Product 5   3925424.542
 5     Product 6   1672229.416
 6     Product 7    889737.555
 7     Product 8   1085037.329
 8     Product 9    710415.405
 9    Product 10    864331.624
 10   Product 11   1230458.484
 11   Product 12   1356976.996
 12   Product 13   3720639.645
 13   Product 14   4028698.409
 14   Product 15   3299478.315
 15   Product 16   2062061.144
 16   Product 17   2119616.824
 17   Product 18   2309499.045
 18   Product 19   1645841.600
 19   Product 20   2067108.120
 20   Product 21    959899.218
 21   Product 22    663601.902
 22   Product 23   1135815.758
 23   Product 24    756557.970
 24   Product 25   5342315.484
 25   Product 26   5685138.270
 26   Product 27    964940.231
 27   Product 28   1003867.767
 28   Product 29    594471.570
 29   Product 30   1011609.684}

In [4]:
df_sales = sheets['Sales Orders']
df_customers = sheets['Customers']
df_regions = sheets['Regions']
df_state = sheets['State Regions']
df_products = sheets['Products']
df_budgets = sheets['2017 Budgets']

In [5]:
print("Sales Orders Shape:", df_sales.shape)
print("Customers Shape:", df_customers.shape)
print("Regions Shape:", df_regions.shape)
print("State Regions Shape:", df_state.shape)
print("Products Shape:", df_products.shape)
print("2017 Budgets Shape:", df_budgets.shape)

Sales Orders Shape: (64104, 12)
Customers Shape: (175, 2)
Regions Shape: (994, 15)
State Regions Shape: (49, 3)
Products Shape: (30, 2)
2017 Budgets Shape: (30, 2)

### Try to check all df

In [6]:
df_sales.head()

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270

In [7]:
df_customers.head()

   Customer Index Customer Names
0               1  Geiss Company
1               2  Jaxbean Group
2               3     Ascend Ltd
3               4      Eire Corp
4               5   Blogtags Ltd

In [8]:
df_regions.head()

,id,name,county,state_code,state,type,latitude,longitude,area_code,population,households,median_income,land_area,water_area,time_zone
0,1,Auburn,Lee County,AL,Alabama,City,32.60986,-85.48078,334,62059,21767,38342,152375113,2646161,America/Chicago
1,2,Birmingham,Shelby County/Jefferson County,AL,Alabama,City,33.52744,-86.79905,205,212461,89972,31061,378353942,6591013,America/Chicago
2,3,Decatur,Limestone County/Morgan County,AL,Alabama,City,34.57332,-86.99214,256,55437,22294,41496,141006257,17594716,America/Chicago
3,4,Dothan,Dale County/Houston County/Henry County,AL,Alabama,City,31.23370,-85.40682,334,68567,25913,42426,232166237,835468,America/Chicago
4,5,Hoover,Shelby County/Jefferson County,AL,Alabama,City,33.37695,-86.80558,205,84848,32789,77146,122016784,2553332,America/Chicago

In [9]:
df_state.head() # indeed to fix columns

      Column1     Column2 Column3
0  State Code       State  Region
1          AL     Alabama   South
2          AR    Arkansas   South
3          AZ     Arizona    West
4          CA  California    West

In [10]:
df_products.head()

   Index Product Name
0      1    Product 1
1      2    Product 2
2      3    Product 3
3      4    Product 4
4      5    Product 5

In [11]:
df_budgets.head()

  Product Name  2017 Budgets
0    Product 1   3016489.209
1    Product 2   3050087.565
2    Product 3   2642352.432
3    Product 4   2885560.824
4    Product 5   3925424.542

### needed to fix columns header of df_state

In [12]:
df_state.head() # we can do that by directly changing the main excel file but that will not a fun :)

      Column1     Column2 Column3
0  State Code       State  Region
1          AL     Alabama   South
2          AR    Arkansas   South
3          AZ     Arizona    West
4          CA  California    West

In [13]:
cols = list(df_state.iloc[0,:])
cols

['State Code', 'State', 'Region']

In [14]:
temp = df_state
temp.columns = cols
df_state = temp.drop(0, axis=0)
df_state.head()
#index is changed !!!

  State Code       State Region
1         AL     Alabama  South
2         AR    Arkansas  South
3         AZ     Arizona   West
4         CA  California   West
5         CO    Colorado   West

In [15]:
df_state = df_state.reset_index(drop=True)
df_state.head()

  State Code       State Region
0         AL     Alabama  South
1         AR    Arkansas  South
2         AZ     Arizona   West
3         CA  California   West
4         CO    Colorado   West

### Check null values in all df's

In [16]:
df_arr = [df_sales, df_customers, df_regions, df_state, df_products, df_budgets]

In [17]:
for i in df_arr:
    print()
    print(i.isnull().sum())
    print()

OrderNumber                  0
OrderDate                    0
Customer Name Index          0
Channel                      0
Currency Code                0
Warehouse Code               0
Delivery Region Index        0
Product Description Index    0
Order Quantity               0
Unit Price                   0
Line Total                   0
Total Unit Cost              0
dtype: int64


Customer Index    0
Customer Names    0
dtype: int64


id               0
name             0
county           0
state_code       0
state            0
type             0
latitude         0
longitude        0
area_code        0
population       0
households       0
median_income    0
land_area        0
water_area       0
time_zone        0
dtype: int64


State Code    0
State         0
Region        0
dtype: int64


Index           0
Product Name    0
dtype: int64


Product Name    0
2017 Budgets    0
dtype: int64

### Data Cleaning and Wrangling

In [18]:
print("hellow")

hellow

##### 1. Merge with costumers

In [19]:
df_sales.head()

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270

In [20]:
df_customers.head()

   Customer Index Customer Names
0               1  Geiss Company
1               2  Jaxbean Group
2               3     Ascend Ltd
3               4      Eire Corp
4               5   Blogtags Ltd

In [21]:
df_sales.merge(
    df_customers, 
    left_on="Customer Name Index", 
    right_on="Customer Index", 
    how="left"
)

,OrderNumber,OrderDate,Customer Name Index,Channel,Currency Code,Warehouse Code,Delivery Region Index,Product Description Index,Order Quantity,Unit Price,Line Total,Total Unit Cost,Customer Index,Customer Names
0,SO - 000225,2014-01-01,126,Wholesale,USD,AXW291,364,27,6,2499.1,14994.6,1824.343,126,Rhynoodle Ltd
1,SO - 0003378,2014-01-01,96,Distributor,USD,AXW291,488,20,11,2351.7,25868.7,1269.918,96,Thoughtmix Ltd
2,SO - 0005126,2014-01-01,8,Wholesale,USD,AXW291,155,26,6,978.2,5869.2,684.740,8,Amerisourc Corp
3,SO - 0005614,2014-01-01,42,Export,USD,AXW291,473,7,7,2338.3,16368.1,1028.852,42,Colgate-Pa Group
4,SO - 0005781,2014-01-01,73,Wholesale,USD,AXW291,256,8,8,2291.4,18331.2,1260.270,73,Deseret Group
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64099,SO - 0007573,2018-02-28,74,Wholesale,USD,AXW291,825,26,12,1815.7,21788.4,980.478,74,Dazzlesphe Corp
64100,SO - 0007706,2018-02-28,51,Export,USD,NXH382,444,21,6,864.3,5185.8,579.081,51,Yombu Corp
64101,SO - 0007718,2018-02-28,136,Distributor,USD,AXW291,312,13,11,3953.0,43483.0,2648.510,136,Bath Group
64102,SO - 0008084,2018-02-28,158,Distributor,USD,AXW291,737,20,7,3959.7,27717.9,2930.178,158,Linklinks Ltd
64103,SO - 0008654,2018-02-28,22,Distributor,USD,AXW291,807,15,8,998.3,7986.4,848.555,22,SAFEWAY Ltd

In [22]:
df_sales= df_sales.merge(
    df_customers, 
    left_on="Customer Name Index", 
    right_on="Customer Index", 
    how="left"
).drop(columns=["Customer Index"])
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Names             64104 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(4), object(5)
memory usage: 6.4+ MB

##### 2. Merge with products

In [23]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Names             64104 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(4), object(5)
memory usage: 6.4+ MB

In [24]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         30 non-null     int64
 1   Product Name  30 non-null     object
dtypes: int64(1), object(1)
memory usage: 612.0+ bytes

In [25]:
df_sales.merge(
    df_products,
    left_on="Product Description Index",
    right_on="Index",
    how="left"
).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Names             64104 non-null  object
 13  Index                      64104 non-null  int64
 14  Product Name               64104 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(5), object(6)
memory usage: 7.3+ MB

In [26]:
df_sales = df_sales.merge(
    df_products,
    left_on="Product Description Index",
    right_on="Index",
    how="left"
).drop(columns=["Index"])
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Names             64104 non-null  object
 13  Product Name               64104 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(4), object(6)
memory usage: 6.8+ MB

##### 3. Merge with region

In [27]:
df_regions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 994 entries, 0 to 993
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             994 non-null    int64
 1   name           994 non-null    object
 2   county         994 non-null    object
 3   state_code     994 non-null    object
 4   state          994 non-null    object
 5   type           994 non-null    object
 6   latitude       994 non-null    float64
 7   longitude      994 non-null    float64
 8   area_code      994 non-null    int64
 9   population     994 non-null    int64
 10  households     994 non-null    int64
 11  median_income  994 non-null    int64
 12  land_area      994 non-null    int64
 13  water_area     994 non-null    int64
 14  time_zone      994 non-null    object
dtypes: float64(2), int64(7), object(6)
memory usage: 116.6+ KB

In [28]:
df_sales = df_sales.merge(
    df_regions,
    left_on="Delivery Region Index",
    right_on="id",
    how="left"
).drop(columns=["id"])
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Names             64104 non-null  object
 13  Product Name               64104 non-null  object
 14  name                       64104 non-null  object
 15  county                     64104 non-null  object
 16  state_code                 64104 non-null  object
 17  state                      64104 non-null  object
 18  type                       64104 non-null  object
 19  latitude                   64104 non-null  float64
 20  longitude                  64104 non-null  float64
 21  area_code                  64104 non-null  int64
 22  population                 64104 non-null  int64
 23  households                 64104 non-null  int64
 24  median_income              64104 non-null  int64
 25  land_area                  64104 non-null  int64
 26  water_area                 64104 non-null  int64
 27  time_zone                  64104 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(10), object(12)
memory usage: 13.7+ MB

In [29]:
df_sales\
    .rename(
        columns={df_sales.columns[14]:"Region Name"}
    )\
    .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Names             64104 non-null  object
 13  Product Name               64104 non-null  object
 14  Region Name                64104 non-null  object
 15  county                     64104 non-null  object
 16  state_code                 64104 non-null  object
 17  state                      64104 non-null  object
 18  type                       64104 non-null  object
 19  latitude                   64104 non-null  float64
 20  longitude                  64104 non-null  float64
 21  area_code                  64104 non-null  int64
 22  population                 64104 non-null  int64
 23  households                 64104 non-null  int64
 24  median_income              64104 non-null  int64
 25  land_area                  64104 non-null  int64
 26  water_area                 64104 non-null  int64
 27  time_zone                  64104 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(10), object(12)
memory usage: 13.7+ MB

In [30]:
df_sales = df_sales\
    .rename(
        columns={df_sales.columns[14]:"Region Name"}
    )
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Names             64104 non-null  object
 13  Product Name               64104 non-null  object
 14  Region Name                64104 non-null  object
 15  county                     64104 non-null  object
 16  state_code                 64104 non-null  object
 17  state                      64104 non-null  object
 18  type                       64104 non-null  object
 19  latitude                   64104 non-null  float64
 20  longitude                  64104 non-null  float64
 21  area_code                  64104 non-null  int64
 22  population                 64104 non-null  int64
 23  households                 64104 non-null  int64
 24  median_income              64104 non-null  int64
 25  land_area                  64104 non-null  int64
 26  water_area                 64104 non-null  int64
 27  time_zone                  64104 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(10), object(12)
memory usage: 13.7+ MB

##### 4. Merge with state

In [31]:
df_state.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   State Code  48 non-null     object
 1   State       48 non-null     object
 2   Region      48 non-null     object
dtypes: object(3)
memory usage: 1.3+ KB

In [32]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Names             64104 non-null  object
 13  Product Name               64104 non-null  object
 14  Region Name                64104 non-null  object
 15  county                     64104 non-null  object
 16  state_code                 64104 non-null  object
 17  state                      64104 non-null  object
 18  type                       64104 non-null  object
 19  latitude                   64104 non-null  float64
 20  longitude                  64104 non-null  float64
 21  area_code                  64104 non-null  int64
 22  population                 64104 non-null  int64
 23  households                 64104 non-null  int64
 24  median_income              64104 non-null  int64
 25  land_area                  64104 non-null  int64
 26  water_area                 64104 non-null  int64
 27  time_zone                  64104 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(10), object(12)
memory usage: 13.7+ MB

In [33]:
df_sales = df_sales.merge(
    df_state,
    left_on="state_code",
    right_on="State Code",
    how="left"
).drop(columns=["State Code", "Region"])
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Names             64104 non-null  object
 13  Product Name               64104 non-null  object
 14  Region Name                64104 non-null  object
 15  county                     64104 non-null  object
 16  state_code                 64104 non-null  object
 17  state                      64104 non-null  object
 18  type                       64104 non-null  object
 19  latitude                   64104 non-null  float64
 20  longitude                  64104 non-null  float64
 21  area_code                  64104 non-null  int64
 22  population                 64104 non-null  int64
 23  households                 64104 non-null  int64
 24  median_income              64104 non-null  int64
 25  land_area                  64104 non-null  int64
 26  water_area                 64104 non-null  int64
 27  time_zone                  64104 non-null  object
 28  State                      64104 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(10), object(13)
memory usage: 14.2+ MB

##### 5. Merge with 2017 buget

In [34]:
df_budgets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product Name  30 non-null     object
 1   2017 Budgets  30 non-null     float64
dtypes: float64(1), object(1)
memory usage: 612.0+ bytes

In [35]:
df_sales.merge(
    df_budgets,
    on='Product Name'
).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Names             64104 non-null  object
 13  Product Name               64104 non-null  object
 14  Region Name                64104 non-null  object
 15  county                     64104 non-null  object
 16  state_code                 64104 non-null  object
 17  state                      64104 non-null  object
 18  type                       64104 non-null  object
 19  latitude                   64104 non-null  float64
 20  longitude                  64104 non-null  float64
 21  area_code                  64104 non-null  int64
 22  population                 64104 non-null  int64
 23  households                 64104 non-null  int64
 24  median_income              64104 non-null  int64
 25  land_area                  64104 non-null  int64
 26  water_area                 64104 non-null  int64
 27  time_zone                  64104 non-null  object
 28  State                      64104 non-null  object
 29  2017 Budgets               64104 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(10), object(13)
memory usage: 14.7+ MB

In [36]:
df_sales = df_sales.merge(
    df_budgets,
    on='Product Name'
)

### Working on cols

#### Select IMP cols

In [37]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   OrderNumber                64104 non-null  object
 1   OrderDate                  64104 non-null  datetime64[ns]
 2   Customer Name Index        64104 non-null  int64
 3   Channel                    64104 non-null  object
 4   Currency Code              64104 non-null  object
 5   Warehouse Code             64104 non-null  object
 6   Delivery Region Index      64104 non-null  int64
 7   Product Description Index  64104 non-null  int64
 8   Order Quantity             64104 non-null  int64
 9   Unit Price                 64104 non-null  float64
 10  Line Total                 64104 non-null  float64
 11  Total Unit Cost            64104 non-null  float64
 12  Customer Names             64104 non-null  object
 13  Product Name               64104 non-null  object
 14  Region Name                64104 non-null  object
 15  county                     64104 non-null  object
 16  state_code                 64104 non-null  object
 17  state                      64104 non-null  object
 18  type                       64104 non-null  object
 19  latitude                   64104 non-null  float64
 20  longitude                  64104 non-null  float64
 21  area_code                  64104 non-null  int64
 22  population                 64104 non-null  int64
 23  households                 64104 non-null  int64
 24  median_income              64104 non-null  int64
 25  land_area                  64104 non-null  int64
 26  water_area                 64104 non-null  int64
 27  time_zone                  64104 non-null  object
 28  State                      64104 non-null  object
 29  2017 Budgets               64104 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(10), object(13)
memory usage: 14.7+ MB

In [38]:
df_sales.columns

Index(['OrderNumber', 'OrderDate', 'Customer Name Index', 'Channel',
       'Currency Code', 'Warehouse Code', 'Delivery Region Index',
       'Product Description Index', 'Order Quantity', 'Unit Price',
       'Line Total', 'Total Unit Cost', 'Customer Names', 'Product Name',
       'Region Name', 'county', 'state_code', 'state', 'type', 'latitude',
       'longitude', 'area_code', 'population', 'households', 'median_income',
       'land_area', 'water_area', 'time_zone', 'State', '2017 Budgets'],
      dtype='object')

In [39]:
df_sales.columns.str.lower()

Index(['ordernumber', 'orderdate', 'customer name index', 'channel',
       'currency code', 'warehouse code', 'delivery region index',
       'product description index', 'order quantity', 'unit price',
       'line total', 'total unit cost', 'customer names', 'product name',
       'region name', 'county', 'state_code', 'state', 'type', 'latitude',
       'longitude', 'area_code', 'population', 'households', 'median_income',
       'land_area', 'water_area', 'time_zone', 'state', '2017 budgets'],
      dtype='object')

In [40]:
df_sales.columns = df_sales.columns.str.lower()
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ordernumber                64104 non-null  object
 1   orderdate                  64104 non-null  datetime64[ns]
 2   customer name index        64104 non-null  int64
 3   channel                    64104 non-null  object
 4   currency code              64104 non-null  object
 5   warehouse code             64104 non-null  object
 6   delivery region index      64104 non-null  int64
 7   product description index  64104 non-null  int64
 8   order quantity             64104 non-null  int64
 9   unit price                 64104 non-null  float64
 10  line total                 64104 non-null  float64
 11  total unit cost            64104 non-null  float64
 12  customer names             64104 non-null  object
 13  product name               64104 non-null  object
 14  region name                64104 non-null  object
 15  county                     64104 non-null  object
 16  state_code                 64104 non-null  object
 17  state                      64104 non-null  object
 18  type                       64104 non-null  object
 19  latitude                   64104 non-null  float64
 20  longitude                  64104 non-null  float64
 21  area_code                  64104 non-null  int64
 22  population                 64104 non-null  int64
 23  households                 64104 non-null  int64
 24  median_income              64104 non-null  int64
 25  land_area                  64104 non-null  int64
 26  water_area                 64104 non-null  int64
 27  time_zone                  64104 non-null  object
 28  state                      64104 non-null  object
 29  2017 budgets               64104 non-null  float64
dtypes: datetime64[ns](1), float64(6), int64(10), object(13)
memory usage: 14.7+ MB

In [41]:
cols_to_keep = [
    'ordernumber',
    'orderdate',
    'customer names',
    'channel',
    'product name',
    'order quantity',
    'unit price',
    'line total',
    'total unit cost',
    'state_code',
    'county',
    'state',
    'region name',
    'latitude',
    '2017 budgets'
]

In [42]:
df = df_sales.loc[:,cols_to_keep]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ordernumber      64104 non-null  object
 1   orderdate        64104 non-null  datetime64[ns]
 2   customer names   64104 non-null  object
 3   channel          64104 non-null  object
 4   product name     64104 non-null  object
 5   order quantity   64104 non-null  int64
 6   unit price       64104 non-null  float64
 7   line total       64104 non-null  float64
 8   total unit cost  64104 non-null  float64
 9   state_code       64104 non-null  object
 10  county           64104 non-null  object
 11  state            64104 non-null  object
 12  state            64104 non-null  object
 13  region name      64104 non-null  object
 14  latitude         64104 non-null  float64
 15  2017 budgets     64104 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(9)
memory usage: 7.8+ MB

In [43]:
df.state

              state         state
0           Georgia       Georgia
1           Indiana       Indiana
2        California    California
3           Indiana       Indiana
4       Connecticut   Connecticut
...             ...           ...
64099  Pennsylvania  Pennsylvania
64100      Illinois      Illinois
64101       Florida       Florida
64102      New York      New York
64103        Oregon        Oregon

[64104 rows x 2 columns]

#### Remove identical colms

In [44]:
df.columns

Index(['ordernumber', 'orderdate', 'customer names', 'channel', 'product name',
       'order quantity', 'unit price', 'line total', 'total unit cost',
       'state_code', 'county', 'state', 'state', 'region name', 'latitude',
       '2017 budgets'],
      dtype='object')

In [45]:
df.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False])

In [46]:
~df.columns.duplicated()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True])

In [49]:
without_dup_col = ~df.columns.duplicated()
df = df.iloc[:,without_dup_col]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ordernumber      64104 non-null  object
 1   orderdate        64104 non-null  datetime64[ns]
 2   customer names   64104 non-null  object
 3   channel          64104 non-null  object
 4   product name     64104 non-null  object
 5   order quantity   64104 non-null  int64
 6   unit price       64104 non-null  float64
 7   line total       64104 non-null  float64
 8   total unit cost  64104 non-null  float64
 9   state_code       64104 non-null  object
 10  county           64104 non-null  object
 11  state            64104 non-null  object
 12  region name      64104 non-null  object
 13  latitude         64104 non-null  float64
 14  2017 budgets     64104 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(8)
memory usage: 7.3+ MB

#### Rename the cols

In [52]:
rename_cols = {
    'ordernumber': 'order_number',
    'orderdate': 'order_date',
    'customer names': 'customer_name',
    'product name': 'product_name',
    'order quantity': 'order_quantity',
    'unit price': 'unit_price',
    'line total': 'revenue',
    'total unit cost': 'cost',
    'state_code': 'state_code',
    'state': 'state_name',
    'latitude': 'lat',
    'longitude': 'lon',
    '2017 budgets': 'budget'
}
df = df.rename(columns=rename_cols)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_number    64104 non-null  object
 1   order_date      64104 non-null  datetime64[ns]
 2   customer_name   64104 non-null  object
 3   channel         64104 non-null  object
 4   product_name    64104 non-null  object
 5   order_quantity  64104 non-null  int64
 6   unit_price      64104 non-null  float64
 7   revenue         64104 non-null  float64
 8   cost            64104 non-null  float64
 9   state_code      64104 non-null  object
 10  county          64104 non-null  object
 11  state_name      64104 non-null  object
 12  region name     64104 non-null  object
 13  lat             64104 non-null  float64
 14  budget          64104 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(8)
memory usage: 7.3+ MB

### Budget only for 2017 Year

In [56]:
df.iloc[:,[0,1,14]].head()

   order_number order_date       budget
0   SO - 000225 2014-01-01   964940.231
1  SO - 0003378 2014-01-01  2067108.120
2  SO - 0005126 2014-01-01  5685138.270
3  SO - 0005614 2014-01-01   889737.555
4  SO - 0005781 2014-01-01  1085037.329

In above example, we can clearly see 2014 year order has some budget value. But as per the excelsheet we only had bugdet of year 2017.

so we need to set the null value for other than 2017 year orders

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_number    64104 non-null  object
 1   order_date      64104 non-null  datetime64[ns]
 2   customer_name   64104 non-null  object
 3   channel         64104 non-null  object
 4   product_name    64104 non-null  object
 5   order_quantity  64104 non-null  int64
 6   unit_price      64104 non-null  float64
 7   revenue         64104 non-null  float64
 8   cost            64104 non-null  float64
 9   state_code      64104 non-null  object
 10  county          64104 non-null  object
 11  state_name      64104 non-null  object
 12  region name     64104 non-null  object
 13  lat             64104 non-null  float64
 14  budget          64104 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(8)
memory usage: 7.3+ MB

In [69]:
df[~(df.order_date=="2017")]

,order_number,order_date,customer_name,channel,product_name,order_quantity,unit_price,revenue,cost,state_code,county,state_name,region name,lat,budget
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Chatham County,Georgia,Savannah,32.08354,964940.231
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Johnson County,Indiana,Greenwood,39.61366,2067108.120
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,Alameda County,California,Pleasanton,37.66243,5685138.270
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Monroe County,Indiana,Bloomington,39.16533,889737.555
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Hartford County,Connecticut,Manchester,41.77524,1085037.329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64099,SO - 0007573,2018-02-28,Dazzlesphe Corp,Wholesale,Product 26,12,1815.7,21788.4,980.478,PA,Bucks County,Pennsylvania,Levittown,40.15511,5685138.270
64100,SO - 0007706,2018-02-28,Yombu Corp,Export,Product 21,6,864.3,5185.8,579.081,IL,Cook County,Illinois,Palatine,42.11030,959899.218
64101,SO - 0007718,2018-02-28,Bath Group,Distributor,Product 13,11,3953.0,43483.0,2648.510,FL,Broward County,Florida,Margate,26.24453,3720639.645
64102,SO - 0008084,2018-02-28,Linklinks Ltd,Distributor,Product 20,7,3959.7,27717.9,2930.178,NY,Erie County,New York,Cheektowaga,42.91002,2067108.120
64103,SO - 0008654,2018-02-28,SAFEWAY Ltd,Distributor,Product 15,8,998.3,7986.4,848.555,OR,Washington County,Oregon,Beaverton,45.48706,3299478.315

In [82]:
other_than_2017 = ~(df.order_date=="2017")
df.loc[other_than_2017, 'budget'] = np.nan
df.head()

,order_number,order_date,customer_name,channel,product_name,order_quantity,unit_price,revenue,cost,state_code,county,state_name,region name,lat,budget
0,SO - 000225,2014-01-01,Rhynoodle Ltd,Wholesale,Product 27,6,2499.1,14994.6,1824.343,GA,Chatham County,Georgia,Savannah,32.08354,NaN
1,SO - 0003378,2014-01-01,Thoughtmix Ltd,Distributor,Product 20,11,2351.7,25868.7,1269.918,IN,Johnson County,Indiana,Greenwood,39.61366,NaN
2,SO - 0005126,2014-01-01,Amerisourc Corp,Wholesale,Product 26,6,978.2,5869.2,684.740,CA,Alameda County,California,Pleasanton,37.66243,NaN
3,SO - 0005614,2014-01-01,Colgate-Pa Group,Export,Product 7,7,2338.3,16368.1,1028.852,IN,Monroe County,Indiana,Bloomington,39.16533,NaN
4,SO - 0005781,2014-01-01,Deseret Group,Wholesale,Product 8,8,2291.4,18331.2,1260.270,CT,Hartford County,Connecticut,Manchester,41.77524,NaN

In [84]:
df.isnull().sum()

order_number          0
order_date            0
customer_name         0
channel               0
product_name          0
order_quantity        0
unit_price            0
revenue               0
cost                  0
state_code            0
county                0
state_name            0
region name           0
lat                   0
budget            64065
dtype: int64

In [84]:
df.isnull().sum()

order_number          0
order_date            0
customer_name         0
channel               0
product_name          0
order_quantity        0
unit_price            0
revenue               0
cost                  0
state_code            0
county                0
state_name            0
region name           0
lat                   0
budget            64065
dtype: int64

In [92]:
df[df.order_date.dt.year == 2017].isnull().sum() ## sala 2017 mai bhee null hie

order_number          0
order_date            0
customer_name         0
channel               0
product_name          0
order_quantity        0
unit_price            0
revenue               0
cost                  0
state_code            0
county                0
state_name            0
region name           0
lat                   0
budget            15224
dtype: int64

### Save the df as csv

In [94]:
df.to_csv('final_df.csv')