In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'./final_df.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      64104 non-null  int64
 1   order_number    64104 non-null  str
 2   order_date      64104 non-null  str
 3   customer_name   64104 non-null  str
 4   channel         64104 non-null  str
 5   product_name    64104 non-null  str
 6   order_quantity  64104 non-null  int64
 7   unit_price      64104 non-null  float64
 8   revenue         64104 non-null  float64
 9   cost            64104 non-null  float64
 10  state_code      64104 non-null  str
 11  county          64104 non-null  str
 12  state_name      64104 non-null  str
 13  region name     64104 non-null  str
 14  lat             64104 non-null  float64
 15  budget          39 non-null     float64
dtypes: float64(5), int64(2), str(9)
memory usage: 13.3 MB

In [3]:
df.columns

Index(['Unnamed: 0', 'order_number', 'order_date', 'customer_name', 'channel',
       'product_name', 'order_quantity', 'unit_price', 'revenue', 'cost',
       'state_code', 'county', 'state_name', 'region name', 'lat', 'budget'],
      dtype='str')

# Sales & Cost Columns — Quick Reference

These four columns describe the relationship between **how many products were sold, the selling price, the cost of the product, and the total cost**.

| Column           | Meaning                                     | Example | Formula                      |
| ---------------- | ------------------------------------------- | ------: | ---------------------------- |
| `order_quantity` | Number of units/products sold in the order  |    `10` | —                            |
| `unit_price`     | Selling price of **1 unit** to the customer |  `₹100` | —                            |
| `unit_cost`      | Business cost of **1 unit**                 |   `₹60` | —                            |
| `total_cost`     | Total cost for all units in the order       |  `₹600` | `order_quantity × unit_cost` |

## Example

Suppose a customer orders **10 units**:

```text
order_quantity = 10
unit_price     = ₹100
unit_cost      = ₹60
```

### Revenue

Revenue is the total amount received from the customer:

```text
Revenue = order_quantity × unit_price

        = 10 × ₹100

        = ₹1,000
```

### Total Cost

Total cost is the total amount the business spends on those 10 units:

```text
Total Cost = order_quantity × unit_cost

           = 10 × ₹60

           = ₹600
```

### Profit

Profit is what remains after subtracting the total cost from revenue:

```text
Profit = Revenue − Total Cost

       = ₹1,000 − ₹600

       = ₹400
```

## Easy way to remember

Think of it like this:

```text
                 1 UNIT
                   │
        ┌──────────┴──────────┐
        │                     │
   Unit Price              Unit Cost
   ₹100                    ₹60
   │                         │
   │                         │
   └────── × Quantity ───────┘
              │
              ▼
        ┌─────────────┐
        │             │
      Revenue      Total Cost
       ₹1,000         ₹600
        │               │
        └───────┬───────┘
                ▼
             Profit
              ₹400
```

### Pandas formulas

```python
# Revenue
df['revenue'] = df['order_quantity'] * df['unit_price']

# Total Cost
df['total_cost'] = df['order_quantity'] * df['unit_cost']

# Profit
df['profit'] = df['revenue'] - df['total_cost']
```

> **Important:** If your dataset has a column named `cost` instead of `unit_cost`, first check whether `cost` represents the **cost per unit** or the **total cost for the order**. Don't automatically multiply it by `order_quantity`.

In [6]:
df.iloc[0:6, 6:10]

   order_quantity  unit_price  revenue      cost
0               6      2499.1  14994.6  1824.343
1              11      2351.7  25868.7  1269.918
2               6       978.2   5869.2   684.740
3               7      2338.3  16368.1  1028.852
4               8      2291.4  18331.2  1260.270
5              11      5219.3  57412.3  4332.019

In [10]:

df = df.rename(columns={
    'cost': 'unit_cost'
})

# Total Cost
df['total_cost'] = df['order_quantity'] * df['unit_cost']

# Profit
df['profit'] = df['revenue'] - df['total_cost']

In [11]:
# Profit Margin Percentage%
df['profit_margit_%'] = (df['profit']/df['revenue'])*100

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64104 entries, 0 to 64103
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       64104 non-null  int64
 1   order_number     64104 non-null  str
 2   order_date       64104 non-null  str
 3   customer_name    64104 non-null  str
 4   channel          64104 non-null  str
 5   product_name     64104 non-null  str
 6   order_quantity   64104 non-null  int64
 7   unit_price       64104 non-null  float64
 8   revenue          64104 non-null  float64
 9   unit_cost        64104 non-null  float64
 10  state_code       64104 non-null  str
 11  county           64104 non-null  str
 12  state_name       64104 non-null  str
 13  region name      64104 non-null  str
 14  lat              64104 non-null  float64
 15  budget           39 non-null     float64
 16  total_cost       64104 non-null  float64
 17  profit           64104 non-null  float64
 18  profit_margit_%  64104 non-null  float64
dtypes: float64(8), int64(2), str(9)
memory usage: 14.8 MB

In [13]:
df.iloc[0:6, [1,5,6,7,8,9,16,17,18]]

,order_number,product_name,order_quantity,unit_price,revenue,unit_cost,total_cost,profit,profit_margit_%
0,SO - 000225,Product 27,6,2499.1,14994.6,1824.343,10946.058,4048.542,27.0
1,SO - 0003378,Product 20,11,2351.7,25868.7,1269.918,13969.098,11899.602,46.0
2,SO - 0005126,Product 26,6,978.2,5869.2,684.740,4108.440,1760.760,30.0
3,SO - 0005614,Product 7,7,2338.3,16368.1,1028.852,7201.964,9166.136,56.0
4,SO - 0005781,Product 8,8,2291.4,18331.2,1260.270,10082.160,8249.040,45.0
5,SO - 0010394,Product 23,11,5219.3,57412.3,4332.019,47652.209,9760.091,17.0